scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Fix SVG Compatibility
        script: |
          # تحديث المكتبة قسرياً لحل مشكلة BaseReactPackage
          npm install react-native-svg@15.1.0
      - name: Generate Android Resources
        script: |
          npx expo prebuild --platform android --no-install
      - name: Build Android APK (Release)
        script: |
          # الدخول وتنظيف Gradle قبل البناء
          cd android && ./gradlew clean && ./gradlew assembleRelease
